export default {
  login: 'swapagarwal',
  id: 2833845,
  node_id: 'MDQ6VXNlcjI4MzM4NDU=',
  avatar_url: 'https://avatars.githubusercontent.com/u/2833845?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/swapagarwal',
  html_url: 'https://github.com/swapagarwal',
  followers_url: 'https://api.github.com/users/swapagarwal/followers',
  following_url:
    'https://api.github.com/users/swapagarwal/following{/other_user}',
  gists_url: 'https://api.github.com/users/swapagarwal/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/swapagarwal/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/swapagarwal/subscriptions',
  organizations_url: 'https://api.github.com/users/swapagarwal/orgs',
  repos_url: 'https://api.github.com/users/swapagarwal/repos',
  events_url: 'https://api.github.com/users/swapagarwal/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/swapagarwal/received_events',
  type: 'User',
  site_admin: false,
  name: 'Swapnil Agarwal',
  company: '@amzn',
  blog: 'swapnil.net',
  location: 'Bangalore, India',
  email: null,
  hireable: true,
  bio:
    'Backend Developer at Amazon | Open Source Contributor at Night | Co-Organizer at Vue Bangalore',
  twitter_username: 'SwapAgarwal',
  public_repos: 85,
  public_gists: 4,
  followers: 973,
  following: 53,
  created_at: '2012-11-19T10:59:56Z',
  updated_at: '2021-04-07T14:29:30Z',
}

// CAN LATER ON CHANGE TO MY OWN DATA
// login: "rajatetc",
// id: 26643075,
// node_id: "MDQ6VXNlcjI2NjQzMDc1",
// avatar_url: "https://avatars.githubusercontent.com/u/26643075?v=4",
// gravatar_id: "",
// url: "https://api.github.com/users/rajatetc",
// html_url: "https://github.com/rajatetc",
// followers_url: "https://api.github.com/users/rajatetc/followers",
// following_url: "https://api.github.com/users/rajatetc/following{/other_user}",
// gists_url: "https://api.github.com/users/rajatetc/gists{/gist_id}",
// starred_url: "https://api.github.com/users/rajatetc/starred{/owner}{/repo}",
// subscriptions_url: "https://api.github.com/users/rajatetc/subscriptions",
// organizations_url: "https://api.github.com/users/rajatetc/orgs",
// repos_url: "https://api.github.com/users/rajatetc/repos",
// events_url: "https://api.github.com/users/rajatetc/events{/privacy}",
// received_events_url: "https://api.github.com/users/rajatetc/received_events",
// type: "User",
// site_admin: false,
// name: "Rajat Gupta",
// company: null,
// blog: "rajatgupta.tech",
// location: null,
// email: null,
// hireable: null,
// bio: "https://www.linkedin.com/in/rajatetc/",
// twitter_username: null,
// public_repos: 34,
// public_gists: 2,
// followers: 1,
// following: 9,
// created_at: "2017-03-24T05:20:56Z",
// updated_at: "2021-04-11T13:44:36Z"
