export default {
  login: 'john-smilga',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/john-smilga',
  html_url: 'https://github.com/john-smilga',
  followers_url: 'https://api.github.com/users/john-smilga/followers',
  following_url:
    'https://api.github.com/users/john-smilga/following{/other_user}',
  gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://api.github.com/users/john-smilga/repos',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'John Smilga',
  company: 'Coding Addict',
  blog: 'www.johnsmilga.com',
  location: 'Los Angeles',
  email: null,
  hireable: null,
  bio: 'Creator of Coding Addict',
  twitter_username: 'john_smilga',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
}

// CAN LATER ON CHANGE TO MY OWN DATA
// login: "rajatetc",
// id: 26643075,
// node_id: "MDQ6VXNlcjI2NjQzMDc1",
// avatar_url: "https://avatars.githubusercontent.com/u/26643075?v=4",
// gravatar_id: "",
// url: "https://api.github.com/users/rajatetc",
// html_url: "https://github.com/rajatetc",
// followers_url: "https://api.github.com/users/rajatetc/followers",
// following_url: "https://api.github.com/users/rajatetc/following{/other_user}",
// gists_url: "https://api.github.com/users/rajatetc/gists{/gist_id}",
// starred_url: "https://api.github.com/users/rajatetc/starred{/owner}{/repo}",
// subscriptions_url: "https://api.github.com/users/rajatetc/subscriptions",
// organizations_url: "https://api.github.com/users/rajatetc/orgs",
// repos_url: "https://api.github.com/users/rajatetc/repos",
// events_url: "https://api.github.com/users/rajatetc/events{/privacy}",
// received_events_url: "https://api.github.com/users/rajatetc/received_events",
// type: "User",
// site_admin: false,
// name: "Rajat Gupta",
// company: null,
// blog: "rajatgupta.tech",
// location: null,
// email: null,
// hireable: null,
// bio: "https://www.linkedin.com/in/rajatetc/",
// twitter_username: null,
// public_repos: 34,
// public_gists: 2,
// followers: 1,
// following: 9,
// created_at: "2017-03-24T05:20:56Z",
// updated_at: "2021-04-11T13:44:36Z"
